name: C/C++ CI

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
  push:
    branches: [ "m2p-4.4-v1.0" ]
  pull_request:
    branches: [ "m2p-4.4-v1.0" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: build
      run: git pull && git checkout m2p-4.4-v1.0 && ./build.sh BPI-M2Z-720P 1
#     - name: configure
#       run: ./configure
#     - name: make
#       run: make
#     - name: make check
#       run: make check
#     - name: make distcheck
#       run: make distcheck
